# Generated by Django 4.0.1 on 2022-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='diagnose_code',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
